### ISSUE TITLE
Stitches TimeCCdEnemyHeroes

### ISSUE THREAD

**Issue by jwfergus** [barrett777/Heroes.ReplayParser#22] opened 2016-07-12 01:16 UTC
I'm finding all my replays with a Stitches have the his (it's?) TimeCCdEnemyHeroes above 24 hours. I attached an example screenshot. It appears to be 24+ hours regardless of some of his CC talent/ult picks so it seems independent of builds. Any thoughts on why this could be?
![image](https://cloud.githubusercontent.com/assets/1657269/16752052/d5b746b8-47a3-11e6-9361-9e3adbe21b2c.png)

**Comment by barrett777** [comment] 2016-07-12 04:02
Yeah, I also believe there is an issue with this statistic.  The issue is on Blizzard's end, though, and I'm not sure if it will get resolved in a way that makes everyone happy

https://github.com/Blizzard/heroprotocol/issues/21

Currently this field is probably just too broad to be useful, which is why I'm not actually using it on HOTSLogs.com now

I'm going to close this issue since the main issue is opened on Blizzard's project, and is out of my hands at this point

**Closed as completed by barrett777** 2016-07-12 04:02 UTC

**Comment by jwfergus** [comment] 2016-07-13 01:58
Makes sense. Thanks for the reply.
